
export const TYPE_COLORS: Record<string, string> = {
  normal: "#A8A77A",
  fire: "#EE8130",
  water: "#6390F0",
  electric: "#F7D02C",
  grass: "#7AC74C",
  ice: "#96D9D6",
  fighting: "#C22E28",
  poison: "#A33EA1",
  ground: "#E2BF65",
  flying: "#A98FF3",
  psychic: "#F95587",
  bug: "#A6B91A",
  rock: "#B6A136",
  ghost: "#735797",
  dragon: "#6F35FC",
  dark: "#705746",
  steel: "#B7B7CE",
  fairy: "#D685AD"
};
export const TYPE_ICONS: Record<string, string> = {
  fire: "/src/assets/icons/types/fire.svg",
  water: "/src/assets/icons/types/water.svg",
  grass: "/src/assets/icons/types/grass.svg",
  electric: "/src/assets/icons/types/electric.svg",
  ground: "/src/assets/icons/types/ground.svg",
  bug: "/src/assets/icons/types/bug.svg",
  dark: "/src/assets/icons/types/dark.svg",
  dragon: "/src/assets/icons/types/dragon.svg",
  fairy: "/src/assets/icons/types/fairy.svg",
  fighting: "/src/assets/icons/types/fighting.svg",
  flying: "/src/assets/icons/types/flying.svg",
  ghost: "/src/assets/icons/types/ghost.svg",
  ice: "/src/assets/icons/types/ice.svg",
  normal: "/src/assets/icons/types/normal.svg",
  poison: "/src/assets/icons/types/poison.svg",
  psychic: "/src/assets/icons/types/psychic.svg",
  rock: "/src/assets/icons/types/rock.svg",
  steel: "/src/assets/icons/types/steel.svg",
};
